"""init

Revision ID: 9c9f2b55406a
Revises:
Create Date: 2026-04-27 19:06:26.438493

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "9c9f2b55406a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
